### ISSUE TITLE
Not able to run electron app on ubuntu 18.04

### ISSUE THREAD

**Issue by mishelen** [bitfinexcom/bfx-hf-ui#132]
Hey! While trying with electron I'm getting next error:

```bash
mishelen@box:~/projects/honey$ npm run dist-linux

> bfx-hf-ui@3.0.5 dist-linux projects/honey
> cross-env electron-builder --linux -c.extraMetadata.main=build/electron.js --publish never

  • electron-builder  version=22.2.0 os=5.0.0-38-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  
  dependencies=bufferutil@4.0.1, utf-8-validate@5.0.2 platform=linux arch=x64
  • packaging platform=linux arch=x64 electron=7.1.8 appOutDir=dist/linux-unpacked
  • asar using is disabled — it is strongly not recommended  
  solution=enable asar and use asarUnpack to unpack files that must be externally available
  ⨯ Application entry file "projects/honey/dist/linux-unpacked/resources/app/build/electron.js" 
  does not exist. Seems like a wrong configuration.  stackTrace=
Error: Application entry file "projects/honey/dist/linux-unpacked/resources/app/build/electron.js" 
  does not exist. Seems like a wrong configuration.
at LinuxPackager.checkFileInPackage (node_modules/app-builder-lib/src/platformPackager.ts:428:15)
at LinuxPackager.sanityCheckPackage (node_modules/app-builder-lib/src/platformPackager.ts:453:5)
at LinuxPackager.doPack (node_modules/app-builder-lib/src/platformPackager.ts:242:5)
at LinuxPackager.pack (node_modules/app-builder-lib/src/platformPackager.ts:114:5)
at Packager.doBuild (node_modules/app-builder-lib/src/packager.ts:437:9)
at executeFinally (node_modules/builder-util/src/promise.ts:12:14)
at Packager._build (node_modules/app-builder-lib/src/packager.ts:366:31)
at Packager.build (node_modules/app-builder-lib/src/packager.ts:330:12)
at executeFinally (node_modules/builder-util/src/promise.ts:12:14)
```

(I cut some paths for readability)

I've already tried to install `asar` globally

**Comment by mishelen** [comment]
Hey, never mind. I forgot to build a project before that.
