### ISSUE TITLE
Issue when upgrading to 3.1.1

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-hf-ui#148]
Hi,

I just updated to 3.1.1 and I came across the following issue when doing npm start:

Starting the development server...

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home///bfx-hf-ui/public/assets/FUN-alt.svg'
    at FSWatcher.start (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1415:11)
    at createFsWatchInstance (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleFile (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:262:21)
    at FSWatcher.<anonymous> (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:495:21)
    at FSReqCallback.oncomplete (fs.js:168:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home///bfx-hf-ui/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home///bfx-hf-ui/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:168:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home//vscode/bfx-hf-ui/public/assets/FUN-alt.svg',
  filename: '/home//vscode/bfx-hf-ui/public/assets/FUN-alt.svg'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bfx-hf-ui@3.1.1 start: `cross-env REACT_APP_DEV=1 REACT_APP_TV_URL=http://localhost:9999 REACT_APP_WSS_URL=ws://localhost:45000 node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bfx-hf-ui@3.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home//.npm/_logs/2020-06-17T17_02_48_564Z-debug.log

**Comment by jcbit** [comment]
Nevermind, that one was my environment acting up. Sorry about that.
