### ISSUE TITLE
[bug-unusable] PingPong AO stops after the first Pong

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#576]
W10, electron bundle as published **3.14.0 + 3.15.0 + 3.16.0** (3.17.0 unable to test)
DEB Linux builds too, consistent behaviour.

Properly reported here:  https://github.com/bitfinexcom/bfx-hf-algo/issues/182 

Apologies, not sure where this should go. Tested more thoroughly now, it seems to have been broken since 28 JUL (bfx-hf-ui-core implementation).

Thank you for reviewing,
miro

**Comment by pointops** [comment]
2021-08-23T18:08:46.197Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close
2021-08-23T18:08:46.198Z bfx:hf:algo:ao-host:ws2:process-message process order:close [0/-0.0002 @ 49447 EXECUTED @ 49447.0(-0.0002)]
2021-08-23T18:08:46.198Z bfx:hf:algo:ao-host triggering order event orders:order_close for AO bfx-ping_pong [gid 1629742102331, o cid 1629742102332, -0.0002 @ 49447 EXECUTED @ 49447.0(-0.0002)]
2021-08-23T18:08:46.198Z bfx:hf:algo:ao-host triggering order event orders:order_fill for AO bfx-ping_pong [gid 1629742102331, o cid 1629742102332, -0.0002 @ 49447 EXECUTED @ 49447.0(-0.0002)]
2021-08-23T18:08:46.198Z bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629742102331]
2021-08-23T18:08:46.198Z bfx:hf:algo:bfx-ping_pong:1629742102331 submitting pong order 49432 for ping 49447
2021-08-23T18:08:46.198Z bfx:hf:algo:bfx-ping_pong:1629742102331 emit exec:order:submit:all [at onOrdersOrderFill (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ping_pong\events\orders_order_fill.js:102:9)]
2021-08-23T18:08:46.198Z bfx:hf:algo:bfx-ping_pong:1629742102331 submitting order LIMIT 0.0002 @ 49432 [gid 1629742126198] 1629742102331
2021-08-23T18:08:46.198Z bfx:hf:algo:bfx-ping_pong:1629742102331 submitOrder (attempt 1): (cid: 1629742126198) LIMIT order on BTC/UST for 0.00020000 @ 49432 [at C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\host\events\submit_all_orders.js:71:11]
2021-08-23T18:08:46.238Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:new
2021-08-23T18:08:46.238Z bfx:hf:algo:bfx-ping_pong:1629742102331 order successfully submitted: LIMIT 0.0002 @ 49432 ACTIVE
2021-08-23T18:08:46.238Z bfx:hf:algo:bfx-ping_pong:1629742102331 updateState [at onOrdersOrderFill (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ping_pong\events\orders_order_fill.js:103:9)]
2021-08-23T18:08:46.238Z bfx:hf:algo:bfx-ping_pong:1629742102331 emit state:update [at updateState (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\host\gen_helpers.js:424:13)]
2021-08-23T18:08:46.238Z bfx:hf:algo:ao-host:ws2:process-message process order:new [0.0002/0.0002 @ 49432 ACTIVE]
2021-08-23T18:08:46.238Z bfx:hf:algo:ao-host triggering order event orders:order_new for AO bfx-ping_pong [gid 1629742102331, o cid 1629742126198, 0.0002 @ 49432 ACTIVE]
2021-08-23T18:09:49.992Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close
2021-08-23T18:09:49.992Z bfx:hf:algo:ao-host:ws2:process-message process order:close [0/0.0002 @ 49432 EXECUTED @ 49432.0(0.0002)]
2021-08-23T18:09:49.992Z bfx:hf:algo:ao-host triggering order event orders:order_close for AO bfx-ping_pong [gid 1629742102331, o cid 1629742126198, 0.0002 @ 49432 EXECUTED @ 49432.0(0.0002)]
2021-08-23T18:09:49.993Z bfx:hf:algo:ao-host triggering order event orders:order_fill for AO bfx-ping_pong [gid 1629742102331, o cid 1629742126198, 0.0002 @ 49432 EXECUTED @ 49432.0(0.0002)]
2021-08-23T18:09:49.993Z bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629742102331]
**2021-08-23T18:09:49.993Z bfx:hf:algo:ao-host:ws2:bind-bus error processing: TypeError: Cannot read property '1' of undefined
    at extract (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ping_pong\util\ping_pong_table.js:14:29)
    at onOrdersOrderFill (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ping_pong\events\orders_order_fill.js:47:42)
    at AOHost.triggerAOEvent (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ao_host.js:824:11)
    at C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ao_host.js:766:20
    at Array.map (<anonymous>)
    at AOHost.triggerOrderEvent (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\ao_host.js:732:33)
    at module.exports (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\host\ws2\process_message.js:111:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async processMessages (C:\Users\the-user\The.Honey.Framework-win\dist\win-unpacked\resources\app\node_modules\bfx-hf-algo\lib\host\ws2\bind_bus.js:30:7)**

**Comment by bhoomij** [comment]
https://github.com/bitfinexcom/bfx-hf-algo/pull/183

**Comment by pointops** [comment]
Tested now on **3.17.0**: same behaviour.

**Comment by pointops** [comment]
Solved with 3.18.x
