### ISSUE TITLE
Error at first startup

### ISSUE THREAD

**Issue by arcanis2k3** [bitfinexcom/bfx-hf-ui#582]
After I choose the local password this occured:

Please, report this issue at https://github.com/bitfinexcom/bfx-hf-ui/issues, 
so we would be able to fix it as soon as possible!
Technical crash info:
Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times
at E (file:///static/js/3.1657fb57.chunk.js:2:5056194)
at Object.activate (file:///static/js/3.1657fb57.chunk.js:2:5058861)
at l.value (file:///static/js/3.1657fb57.chunk.js:2:2512457)
at l.value (file:///static/js/3.1657fb57.chunk.js:2:2512561)
at fs (file:///static/js/3.1657fb57.chunk.js:2:2763700)
at xl (file:///static/js/3.1657fb57.chunk.js:2:2780819)
at t.unstable_runWithPriority (file:///static/js/3.1657fb57.chunk.js:2:2800213)
at zi (file:///static/js/3.1657fb57.chunk.js:2:2722384)
at kl (file:///static/js/3.1657fb57.chunk.js:2:2777360)
at fl (file:///static/js/3.1657fb57.chunk.js:2:2773446)
at file:///static/js/3.1657fb57.chunk.js:2:2722607
at t.unstable_runWithPriority (file:///static/js/3.1657fb57.chunk.js:2:2800213)
at zi (file:///static/js/3.1657fb57.chunk.js:2:2722384)
at Gi (file:///static/js/3.1657fb57.chunk.js:2:2722552)
at qi (file:///static/js/3.1657fb57.chunk.js:2:2722487)
at ll (file:///static/js/3.1657fb57.chunk.js:2:2770590)
at xo (file:///static/js/3.1657fb57.chunk.js:2:2742164)
at file:///static/js/3.1657fb57.chunk.js:2:126711

**Comment by bhoomij** [comment]
merged fix on master, will be available in next release `3.17.0`
