### ISSUE TITLE
Error: spawn concurrently ENOENT

### ISSUE THREAD

**Issue by Doweig** [bitfinexcom/bfx-hf-ui#72]
Trying to run the app on my laptop, I did clone the repo and follow the install procedure.
`npm run build` went fine but `npm run start-server` is crashing.

Error:

```
$> npm run start-server

> bfx-hf-ui@3.0.0 start-server /Users/doweig/dev/satoshi_cenobium/bfx-hf-ui
> cross-env concurrently --kill-others "npm run start-api-server"

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn concurrently ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Full log:

```
$> cat /Users/doweig/.npm/_logs/2020-01-20T08_51_23_455Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-server' ]
2 info using npm@6.10.1
3 info using node@v10.13.0
4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
5 info lifecycle bfx-hf-ui@3.0.0~prestart-server: bfx-hf-ui@3.0.0
6 info lifecycle bfx-hf-ui@3.0.0~start-server: bfx-hf-ui@3.0.0
7 verbose lifecycle bfx-hf-ui@3.0.0~start-server: unsafe-perm in lifecycle true
8 verbose lifecycle bfx-hf-ui@3.0.0~start-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/doweig/dev/satoshi_cenobium/bfx-hf-ui/node_modules/.bin:/Users/doweig/dev/satoshi_cenobium/bitcoin-0.17.1/bin:/Users/doweig/dev/satoshi_cenobium/lnd-darwin-amd64-v0.7.0-beta:/Users/doweig/.yarn/bin:/Users/doweig/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle bfx-hf-ui@3.0.0~start-server: CWD: /Users/doweig/dev/satoshi_cenobium/bfx-hf-ui
10 silly lifecycle bfx-hf-ui@3.0.0~start-server: Args: [ '-c',
10 silly lifecycle   'cross-env concurrently --kill-others "npm run start-api-server"' ]
11 silly lifecycle bfx-hf-ui@3.0.0~start-server: Returned: code: 1  signal: null
12 info lifecycle bfx-hf-ui@3.0.0~start-server: Failed to exec start-server script
13 verbose stack Error: bfx-hf-ui@3.0.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid bfx-hf-ui@3.0.0
15 verbose cwd /Users/doweig/dev/satoshi_cenobium/bfx-hf-ui
16 verbose Darwin 19.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-server"
18 verbose node v10.13.0
19 verbose npm  v6.10.1
20 error code ELIFECYCLE
21 error errno 1
22 error bfx-hf-ui@3.0.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
22 error Exit status 1
23 error Failed at the bfx-hf-ui@3.0.0 start-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Versions:

```
➜  bfx-hf-ui git:(master) ✗ node --version
v10.13.0
➜  bfx-hf-ui git:(master) ✗ npm --version
6.10.1
➜  bfx-hf-ui git:(master) ✗ yarn --version
1.13.0
```
on MacOS 10.15.2

**Comment by FiveBoroughs** [comment]
Same Error, Ubuntu 18.04

Temporary fix:
Removing `cross-env concurrently --kill-others` from `package.json`

**Comment by f3rno** [comment]
Very strange; we are wrapping up a new release for next week, `master` is a bit behind now. It may be fixed there, I will ping here when it's out.

**Comment by FiveBoroughs** [comment]
@olexiyb got it, we're just missing the `concurrently` package
