### ISSUE TITLE
[bug] dist-linux scipt fails ('electron.js missing)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#761]
Github clone on 2022-11-15 @ 13:20 UTC

-------------- terminal dump --------------
user@Machine:~/bfx-hf-ui$ npm run dist-linux

> bfx-hf-ui@3.31.1 dist-linux
> cross-env electron-builder --linux -c.extraMetadata.main=build/electron.js --publish never && npm run package-linux

  • electron-builder  version=22.14.13 os=5.10.16.3-microsoft-standard-WSL2
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=13.6.9 appOutDir=dist/linux-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  **⨯ Application entry file "/home/user/bfx-hf-ui/dist/linux-unpacked/resources/app/build/electron.js" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "/home/user/bfx-hf-ui/dist/linux-unpacked/resources/app/build/electron.js" does not exist. Seems like a wrong configuration.**
    at LinuxPackager.checkFileInPackage (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/platformPackager.ts:526:15)
    at LinuxPackager.sanityCheckPackage (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/platformPackager.ts:549:5)
    at LinuxPackager.doPack (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/platformPackager.ts:310:5)
    at LinuxPackager.pack (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/platformPackager.ts:136:5)
    at Packager.doBuild (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/home/user/bfx-hf-ui/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/home/user/bfx-hf-ui/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/home/user/bfx-hf-ui/node_modules/builder-util/src/promise.ts:12:14)
user@Machine:~/bfx-hf-ui$

**Comment by pointops** [comment]
unable to reproduce
